description: Repository for the CLOVER-energy Github organisation
email: organisation.email@top.level.domain
github:
  repository_url: https://github.com/CLOVER-energy/CLOVER
  wiki_url: https://github.com/CLOVER-energy/CLOVER/wiki
  zip_url: https://github.com/CLOVER-energy/CLOVER/archive/refs/heads/master.zip
title: CLOVER
show_downloads: true
remote_theme: pages-themes/minimal@v0.2.0
logo: logo_inverted.png
plugins:
- jekyll-remote-theme
