description: Repository for the CLOVER-energy Github organisation
email: organisation.email@top.level.domain
github: https://github.com/CLOVER-energy/CLOVER
title: CLOVER
show_downloads: true
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
